# Generated by Django 4.1.4 on 2023-01-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_item_bid_bid_alter_bid_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='number',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
