# Generated by Django 4.1.4 on 2023-01-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_time_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('categoryName',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
