# Generated by Django 4.1.4 on 2023-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_time_alter_comment_time_alter_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
