# Generated by Django 4.1.4 on 2023-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_num_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='num_bids',
            field=models.IntegerField(default=0),
        ),
    ]
