# Generated by Django 4.1.4 on 2023-01-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_num_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='num_bids',
            new_name='bid_count',
        ),
    ]
