# Generated by Django 4.1.4 on 2023-01-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_bid_listing_alter_bid_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bid_count',
        ),
    ]
